namespace :rabbitmq do
  desc "Setup routing"
  task :setup do
    require "bunny"
    conn = Bunny.new(hostname: "192.168.99.100")
    conn.start
    ch = conn.create_channel
    x = ch.fanout("blog.posts")
    queue = ch.queue("dashboard.posts", durable: true)
    queue.bind("blog.posts")
    conn.close
  end
end